/**
 * Transfer State Machine Enum
 */
export const TransferState = Object.freeze({
  IDLE: 'IDLE',
  CONNECTING: 'CONNECTING',
  CONNECTED: 'CONNECTED',
  NEGOTIATING: 'NEGOTIATING',
  WAITING_FOR_ACCEPT: 'WAITING_FOR_ACCEPT',
  TRANSFERRING: 'TRANSFERRING',
  PAUSED: 'PAUSED',
  VERIFYING: 'VERIFYING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  DISCONNECTED: 'DISCONNECTED',
  RESUMING: 'RESUMING'
});

/**
 * Optical Link Status Enum
 */
export const LinkStatus = Object.freeze({
  DISCONNECTED: 'DISCONNECTED',
  SEARCHING: 'SEARCHING',
  CONNECTING: 'CONNECTING',
  ACTIVE: 'ACTIVE',
  DEGRADED: 'DEGRADED',
  ERROR: 'ERROR'
});

/**
 * Structured Error Codes
 */
export const ErrorCode = Object.freeze({
  OPTICAL_LINK_LOST: 'OPTICAL_LINK_LOST',
  CRC_MISMATCH: 'CRC_MISMATCH',
  TIMEOUT: 'TIMEOUT',
  SECURITY_VIOLATION: 'SECURITY_VIOLATION',
  STORAGE_FULL: 'STORAGE_FULL',
  INTEGRITY_FAILED: 'INTEGRITY_FAILED',
  UNSUPPORTED_PROTOCOL: 'UNSUPPORTED_PROTOCOL',
  TRANSFER_CANCELLED: 'TRANSFER_CANCELLED',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR'
});

/**
 * Log Levels
 */
export const LogLevel = Object.freeze({
  DEBUG: 0,
  INFO: 1,
  WARN: 2,
  ERROR: 3
});
